apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-crb-manager
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-crb-manager
subjects:
- kind: ServiceAccount
  name: kube-crb-manager
  namespace: kube-system
