stages:
  - test
  - build

test-golint:
  stage: test
  image: golangci/golangci-lint:v1.27.0
  script:
    - golangci-lint run -v

build-develop:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/kube-crb-manager:develop-$CI_COMMIT_SHORT_SHA" -f Dockerfile .
    - docker push "$CI_REGISTRY/kube-crb-manager:develop-$CI_COMMIT_SHORT_SHA"
